Sorcery/sorcery

- spec/controllers/controller_oauth2_spec.rb
- spec/shared_examples/user_shared_examples.rb
After run specs, there remains left users and version in schema_migrations.
```
sqlite> .tables
schema_migrations  users
sqlite>
sqlite> select * from users;
sqlite>
sqlite> select * from schema_migrations;
20101224223620
20101224223622
```
It prevents from running test suites after modifying a file in `spec/rails_app/db/migrate/core` or `spec/rails_app/db/migrate/activation`.
Looking into specs, I found 2 files `spec/controllers/controller_oauth2_spec.rb` and  `spec/shared_examples/user_shared_examples.rb` are the cause.
First in `spec/controllers/controller_oauth2_spec.rb`, I add rollback of external just before rollback of activation. The current version when rollback of activation is exectuted is different.
The versions then is below:
```
sqlite> select * from schema_migrations; …
```
>  There remains left users and version in schema_migrations after running test suites.

- lib/sorcery/model/temporary_token.rb
> Use urlsafe_base64 for url sensitive chars

- lib/sorcery/providers/linkedin.rb
I fixed a bug. Until then, specs passed due to exec order of 'or'.
> Fixes wrong use of include?()

- .travis.yml
- CHANGELOG.md
- Gemfile
- lib/sorcery/test_helpers/internal/rails.rb
- sorcery.gemspec
- spec/controllers/controller_activity_logging_spec.rb
- spec/controllers/controller_brute_force_protection_spec.rb
- spec/controllers/controller_http_basic_auth_spec.rb
- spec/controllers/controller_oauth2_spec.rb
- spec/controllers/controller_oauth_spec.rb
- spec/controllers/controller_remember_me_spec.rb
- spec/controllers/controller_session_timeout_spec.rb
- spec/controllers/controller_spec.rb
- spec/rails_app/app/controllers/sorcery_controller.rb
- spec/rails_app/config/initializers/compatible_legacy_migration.rb
- spec/rails_app/db/migrate/activation/20101224223622_add_activation_to_users.rb
- spec/rails_app/db/migrate/activity_logging/20101224223624_add_activity_logging_to_users.rb
- spec/rails_app/db/migrate/brute_force_protection/20101224223626_add_brute_force_protection_to_users.rb
- spec/rails_app/db/migrate/core/20101224223620_create_users.rb
- spec/rails_app/db/migrate/external/20101224223628_create_authentications_and_user_providers.rb
- spec/rails_app/db/migrate/remember_me/20101224223623_add_remember_me_token_to_users.rb
- spec/rails_app/db/migrate/reset_password/20101224223622_add_reset_password_to_users.rb
- spec/spec_helper.rb
This PR pass all tests and fix deprecation warnings on Rails 5.
In the process, I removed test of rails 4.0.1. https://github.com/Sorcery/sorcery/commit/b69a89bbe0e6ed2aac6a9fc3694ce1bfaf248a71
Because `render plain` did not exist on rails 4.0.1, but It needs on Rails 5. https://github.com/Sorcery/sorcery/commit/4fc164f2e285ca1f85d16497113b8730bedd3041
I can also fix this problem with the way like [this](https://github.com/Sorcery/sorcery/compare/master...kyuden:rails5?expand=1#diff-d0d1d0d5ee17b0aee49ab5b831d7e9a3R66) , but rails 4.0.1 have not been maintained yet. So I removed test of rails 4.0.1.  What do you think?
related: https://github.com/Sorcery/sorcery/issues/20
edit:
I noticed test of rails 4.0.1 don't need to be drop. So, I added a test of rails 5 only.
> Test against Rails 5 by default

- .travis.yml
- CHANGELOG.md
- lib/sorcery/crypto_providers/aes256.rb
- sorcery.gemspec
- spec/sorcery_crypto_providers_spec.rb
Ruby 2.4.0 Released. :christmas_tree:
This PR fixed mainly deprecation warnings on Ruby 2.4. 
- Fix warning of deprecated constant.
- Test against ruby 2.4.0 on CI.
In addition, I cleaned sorcery.gemspec
- Drop json gem dependency for development
- The dependency for json gem is custom for Ruby 1.8. We should use json of a standard library.
- Drop abstract gem dependency for development
> Support Ruby 2.4

- CHANGELOG.md
- lib/sorcery/version.rb
- sorcery.gemspec
I think we should be just about ready for the 0.10.0 release. Are there any other things we'd like to get in before doing so?
> Increment version number to 0.10.0

- .gitignore
- CHANGELOG.md
- lib/generators/sorcery/templates/initializer.rb
- lib/sorcery/controller/submodules/external.rb
- lib/sorcery/providers/graph.rb
- lib/sorcery/providers/microsoft.rb
- lib/sorcery/version.rb
- sorcery.gemspec
- spec/controllers/controller_oauth2_spec.rb
- spec/rails_app/app/controllers/sorcery_controller.rb
- spec/rails_app/config/routes.rb
- spec/spec_helper.rb
DO NOT MERGE, still working on this.
> Add Microsoft Graph Provider

- CHANGELOG.md
- lib/sorcery.rb
- lib/sorcery/adapters/mongoid_adapter.rb
- lib/sorcery/version.rb
There were plans on moving adapters out, but until that actually happens we need to keep this in otherwise MongoID will break for users. Interestingly, the additional adapters were removed in 2014, but were still a part of the v0.9.1 release.
Note to users experiencing issues: After updating to Sorcery v0.10.3, you must `include Mongoid::Document` _before_ you call `authenticates_with_sorcery!`
I have not thoroughly tested this, any feedback is appreciated.
Fixes #35
> Re-add MongoID Adapter

- lib/generators/sorcery/templates/initializer.rb
As I found the undocumented option which is about Github's scope with external module in Github OAuth. I think it is better if this pull request is accept, because it takes time to find the option out if someone who uses Github OAuth with external module and want to manage the Github's scope.
I don't want to change original behavior when ` comment out ` of added option is remove, so default value is blank. (blank scope is called [ ` no scope ` ](https://developer.github.com/v3/oauth/#scopes).)
refs: #48
> Add github scope option to initializer.rb

- lib/sorcery/controller.rb
- lib/sorcery/model.rb
- lib/sorcery/model/submodules/brute_force_protection.rb
- lib/sorcery/model/submodules/reset_password.rb
- lib/sorcery/model/submodules/user_activation.rb
- lib/sorcery/model/temporary_token.rb
- spec/controllers/controller_brute_force_protection_spec.rb
- spec/controllers/controller_remember_me_spec.rb
- spec/controllers/controller_session_timeout_spec.rb
- spec/controllers/controller_spec.rb
- spec/shared_examples/user_activation_shared_examples.rb
- spec/shared_examples/user_reset_password_shared_examples.rb
- spec/shared_examples/user_shared_examples.rb
This was never merged into the old repo, but I still think it's a worthwhile change.
https://github.com/NoamB/sorcery/pull/704
These changes allow a website to tell the difference between a wrong password, a locked account, and an inactive account, so that the user can be sent to a "resend activation" or "unlock account" page when necessary.
> Resurrect block authentication

- lib/generators/sorcery/templates/initializer.rb
- lib/sorcery/providers/facebook.rb
With Facebook deprecating version 2.2 of the Graph API, they now only return json access tokens.
See https://developers.facebook.com/docs/apps/changelog
[Oauth Access Token] Format - The response format of https://www.facebook.com/v2.3/oauth/access_token returned when you exchange a code for an access_token now return valid JSON instead of being URL encoded. The new format of this response is {"access_token": {TOKEN}, "token_type":{TYPE}, "expires_in":{TIME}}. We made this update to be compliant with section 5.1 of RFC 6749.
> Allow changing facebook parser and change default parser to json

- lib/sorcery/test_helpers/internal.rb
I ran the single file test
`rspec spec/controllers/controller_spec.rb`
And got the error below:
```
NameError:
constant Object::User not defined
```        
If you call `remove_const` before the first constant reference, a name error occurs.
Because constant autoloading in Rails is implemented with Module#const_missing.
I Changed  `reload_user_class` to refer ‘User’ constant before reload.
> Fixed : “NameError: constant Object::User not defined” error message when you run the single spec file

- CHANGELOG.md
- lib/generators/sorcery/templates/initializer.rb
This adds an example for user_info_path for facebook for the config generator. Should address this issue: https://github.com/Sorcery/sorcery/issues/62
> add user_info_path for facebook in the config generator

- .travis.yml
Travis CI tests ruby 2.0 and 2.1, which forces to use hash rocket. I think sorcery needs the code guideline by introducing Rubocop in the future, but this old way notation prevents it.
It's also natural to make users doubt whether this product is still maintained by supporting too old ruby versions. Of course I know sorcery is actively maintained, and it's not good.
I confirm tests are all green.
Thanks for reviewing.
> Delete unsupported ruby versions from CI.

- CHANGELOG.md
- lib/generators/sorcery/templates/initializer.rb
- lib/sorcery/model/config.rb
- lib/sorcery/model/temporary_token.rb
- spec/sorcery_temporary_token_spec.rb
To increase security, I want to change token randomness by configuration 🔑
> Configurable token randomness

- CHANGELOG.md
- lib/sorcery/controller/submodules/external.rb
- lib/sorcery/model/submodules/external.rb
Currently there's no way to build a user from an oauth callback, you have to either manually map the data or create the user with create_from.
> Add build_from method

- lib/sorcery/controller.rb
I add these error, because earlier, if we forgot to define user_class (f.e. not add sorcery.rb to initializers) we got just NameError, which not easy to google for newbie developers.
> add new ArgumentError for not defined user_class in config

- lib/generators/sorcery/templates/initializer.rb
Most users use BCrypt and don't change defaults, which means that the default value would be 10. That makes tests run slowly.
Setting the number of stretches in test env to 1 can decrease the test suite up to 2x times (although BCrypt minimal cost is 4, we can use 1 for SHA algorithms).
> Set user.stretches to 1 in test env by default

- lib/sorcery/adapters/active_record_adapter.rb
This is the PR for the [issue#87](https://github.com/Sorcery/sorcery/issues/87)
See there for details.
Another choice of implemention is like this:
```
@model.class.find_by(:"#{primary_key}" =>
@model.send(:"#{primary_key}")).update(attrs)
```
but for some reasons I don't adopt it.
First it makes 2 queries instead of one.
Secondly it has potential risk to race conditions.
> Make `#update_attributes` behavior identical to `#update`

- lib/generators/sorcery/templates/migration/magic_login.rb
I use rails 5.1 and sorcery(github head).
so, I Migrated with this command: 
```
$ bundle exec rails g sorcery:install core magic_login --model Authentication
$ bundle exec rails db:migration
```
At that time, a migration error occurred using "magic login" module.
The problem was this part, and it succeeded when corrected.
> fix magic login migration.

- lib/generators/sorcery/templates/initializer.rb
- lib/generators/sorcery/templates/migration/reset_password.rb
- lib/sorcery/model/submodules/reset_password.rb
- spec/rails_app/db/migrate/reset_password/20101224223622_add_reset_password_to_users.rb
- spec/shared_examples/user_reset_password_shared_examples.rb
Fix [Password reset token leak via HTTP referer](https://github.com/Sorcery/sorcery/issues/40).
This change requires to update [the documentation](https://github.com/Sorcery/sorcery/wiki/Reset-password) accordingly, and I will explain how to fix it in implementation and the documentation (written below).
I follow the step of the first direction mentioned in [Is Your Site Leaking Password Reset Links?](https://robots.thoughtbot.com/is-your-site-leaking-password-reset-links#testing-your-site): 
>Update the passwords#edit controller action so it immediately invalidates the password reset token in the request and generates a new one that is used in the form action. The Referer will still contain the original password reset token, but the token is no longer valid.
* Add …
> Fix issue #40

- lib/sorcery.rb
- lib/sorcery/test_helpers/rails/request.rb
There is no test helper for request specs now. It' not convenient officially recommending to write request specs to a new rails app.
If this PR is merged, I will add the documentation how to use the helper.
Thank you for review.
> Add the request spec helper method, #login_user.

- lib/generators/sorcery/install_generator.rb
`Sorcery::Generators::InstallGenerator::ActiveRecord` is not defined
and the purpose of this guard is to know whether orm is ActiveRecord or not.
Therefore, return early when top-level ActiveRecord is not defined.
This patch will solve #119
> Fix for not-copied migration files

- lib/sorcery/engine.rb
Rails API apps use the lighter alternative to ActionController::Base.
This adds support for injecting these helpers into either action
controller base class that the consuming application happens to inherit
from.
This is a step towards full support in rails api mode.
> Support injecting helpers into ActionController::API

- lib/sorcery/adapters/active_record_adapter.rb
- lib/sorcery/adapters/mongoid_adapter.rb
- lib/sorcery/model/submodules/reset_password.rb
- lib/sorcery/model/submodules/user_activation.rb
- spec/spec_helper.rb
Use `after_commit on: :create` instead of `after_create` callback for sending activation email. It's necessary because of `after_create` is located in a transaction. There is no guarantee that user will exist when email will start building.
More details http://codebeerstartups.com/2012/11/use-after_commit-instead-of-active-record-callbacks-to-avoid-unexpected-errors/
Also added a patch to mongo `define callback`. Let me know if you need more info about this issue.
> send activation email after the commit in transactional databases

- README.md
- lib/generators/sorcery/templates/initializer.rb
- lib/sorcery/controller/submodules/session_timeout.rb
- spec/controllers/controller_session_timeout_spec.rb
- spec/rails_app/app/controllers/sorcery_controller.rb
- spec/rails_app/config/routes.rb
- spec/rails_app/db/migrate/invalidate_active_sessions/20180221093235_add_invalidate_active_sessions_before_to_users.rb
Add a configurable `invalid_active_sessions!` method to the session_timeouts module. Configurable, but expects an `invalidate_sessions_before` timestamp column on user. Does not invalidate the session if `invalidate_sessions_before` is not set meaning that if it is deployed it won't log out currently logged in users.
Update the gem version if necessary. Because this is opt in, it should not be a breaking change.
@arnvald
> Add an opt in invalidate_active_sessions!  method to session timeout

- lib/sorcery/controller.rb
- lib/sorcery/controller/submodules/remember_me.rb
When overriding the `#auto_login` method when implementing our own
session handling we never got passed the `should_remember` value from
the `#login` method.
The `Sorcery::Controller::Submodules::RememberMe` never used the value
of the `should_remember` arguments passed to the `#auto_login` method
and instead relied on a callback being executed.
This commits removes the callback and instead calls the `#remember_me!`
method from the `#auto_login` method instead.
> Pass along `remember_me` to `#auto_login`

- lib/sorcery/controller.rb
- lib/sorcery/controller/config.rb
- lib/sorcery/controller/submodules/remember_me.rb
- lib/sorcery/controller/submodules/session_timeout.rb
- spec/controllers/controller_remember_me_spec.rb
- spec/controllers/controller_session_timeout_spec.rb
Before this, an unlimited session was created on login via the remember me cookie, even though the SessionTimeout module is active.
I introduced a new callback (after_remember_me) to allow updating the session timeout on login from cookie without tight coupling both submodules.
It seems like all callbacks / interactions between the submodules are not tested, so I'm not sure if I should test here.. So I just added expectations for calling the specific (callback) methods.
> Respect SessionTimeout on login via RememberMe

- CHANGELOG.md
- lib/generators/sorcery/templates/initializer.rb
In facebook, `publish_actions` permission has been deleted.
https://developers.facebook.com/docs/graph-api/changelog/breaking-changes?locale=en_US
So, it is not good that `publish_actions` still exists in template file.
> Remove `publish_actions` permission for facebook

- lib/sorcery/engine.rb
Fixes #137.
This PR correctly loads sorcery.
> Fix rails injection

- Gemfile
- lib/sorcery/controller/submodules/activity_logging.rb
- lib/sorcery/controller/submodules/brute_force_protection.rb
- lib/sorcery/controller/submodules/http_basic_auth.rb
- lib/sorcery/controller/submodules/remember_me.rb
- lib/sorcery/controller/submodules/session_timeout.rb
- lib/sorcery/engine.rb
Failed_logins_count is incremented by 2 when login failed.
login failed request SQL log
```
CACHE User Load (0.0ms)  SELECT  `users`.* FROM `users` WHERE `users`.`type` IN ('User') AND `users`.`deleted_at` IS NULL AND `users`.`email` = 'unko@example.com' ORDER BY `users`.`id` ASC LIMIT 1  [["LIMIT", 1]]
SQL (5.8ms)  UPDATE `users` SET `failed_logins_count` = COALESCE(`failed_logins_count`, 0) + 1 WHERE `users`.`type` IN ('User') AND `users`.`id` = 1702
User Load (0.7ms)  SELECT  `users`.* FROM `users` WHERE `users`.`type` IN ('User') AND `users`.`deleted_at` IS NULL AND `users`.`email` = 'unko@example.com' ORDER BY `users`.`id` ASC LIMIT 1
SQL (3.2ms)  UPDATE `users` SET `failed_logins_count` = COALESCE(`failed_logins_count`, 0) + 1 WHERE `users`.`type` IN ('User') AND `users`.`id` = 1702 …
```
> update_failed_logins_count is called twice when login failed

- lib/generators/sorcery/templates/initializer.rb
I've tried to make the documentation in the `initializer.rb` file (which gets copied to `config/sorcery.rb` on install) clearer for new users. 
I've also added the `magic_login` submodule to the list, since that seems like a recent addition.
> Clean up initializer comments

- lib/sorcery/crypto_providers/bcrypt.rb
- lib/sorcery/model.rb
- lib/sorcery/model/config.rb
- spec/shared_examples/user_shared_examples.rb
- spec/sorcery_crypto_providers_spec.rb
Hello, thank you very much for the great work to maintain this great gem!
This PR introduces a small yet (imho) some important updates that hopefully helps Sorcery to enhance its password security.
This patch adds an option that allows users to provide app-specific secret token (often called as 'pepper') with BCrypt, the default crypt-provider, which is currently missing (explained below).
To ensure compatibility, this change only takes place when the new option 'pepper' is provided - most importantly, this change **does NOT affect** on any of the gem's behavior, for those who have already set salt_join_token but leaves pepper option unset.
Tests are added to cover several BCrypt cases that have been missing, as well as this new feature.
Currently the config option 'salt_join_token' [has …
> allow BCrypt to have app-specific secret token

- lib/sorcery/controller/submodules/external.rb
- lib/sorcery/version.rb
- spec/providers/example_provider_spec.rb
- spec/providers/example_spec.rb
- spec/support/providers/example.rb
- spec/support/providers/example_provider.rb
Currently sorcery will not handle custom providers with names like: ExampleProvider. config.example_provider would search for a class called Example_provider rather than ExampleProvider. Using .classify rather than .capitalize will fix this.
I've added an example provider implementation under the spec/support directory, and have a test that ensures that it is loaded properly via config. The existing tests for existing providers are also coming back with successes.
> Allow for custom providers with multi-word class names.

- lib/sorcery/controller/submodules/remember_me.rb
Hello!
I fixed `Remember Me` submodule.
When using `Remember Me` submodule, `NoMethodError` occurs on controllers that do not define cookies such as API.
I fixed to read cookies only if cookies are defined.
> Ignore cookies when undefined cookies in Remember Me

- lib/generators/sorcery/templates/initializer.rb
- lib/sorcery/providers/linkedin.rb
As per https://github.com/Sorcery/sorcery/blob/master/lib/generators/sorcery/templates/migration/core.rb user email is a mandatory field in the DB. Thus, the recent fix for LinkedIn provider will produce an error when you try to register a new profile with it.
This fix loads user email from the additional endpoint in LinkedIn API v2 following this description: https://docs.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/sign-in-with-linkedin?context=linkedin/consumer/context#retrieving-member-email-address
> Load user email in LinkedIn provider

- lib/sorcery/providers/vk.rb
- spec/controllers/controller_oauth2_spec.rb
VK has changed the API and it returns `user_info` in such way
```
{
email: 'someone@vk.com',
id: 12300321
}
```
Therefore `user_hash[:user_info]['uid']` is `nil` and sorcery does not create authentication for user. This patch should fix this. 
Not sure how to add spec for this case. Let me know if you have any questions.
> Use id instead of uid for VK provider

- lib/generators/sorcery/templates/initializer.rb
- lib/sorcery/controller/submodules/external.rb
- lib/sorcery/providers/discord.rb
- spec/controllers/controller_oauth2_spec.rb
- spec/rails_app/app/controllers/sorcery_controller.rb
- spec/rails_app/config/routes.rb
Hello, developers of Sorcery. This gem is very helpful.
By the way, I propose a new provider of Discord. This is what I need, and I'm sure it will be useful to other Sorcery users.
About Discord's OAuth 2.0 documentation is here.
https://discordapp.com/developers/docs/topics/oauth2
I know you are busy, but could you take a look at it?
Thank you.
> Add discord provider

- spec/controllers/controller_remember_me_spec.rb
- spec/rails_app/app/controllers/sorcery_controller.rb
- spec/rails_app/config/routes.rb
This PR completes two test cases that were marked as `pending`.
> Add forget_me! and force_forget_me! test cases

- lib/sorcery/model.rb
The authenticate method previously would return before callbacks executed if an
invalid password was provided, which causes the brute force protection to only
work for the first lockout period, and only resets after a successful login.
Fixes #231
> Fix brute force vuln due to callbacks not being ran

- lib/sorcery/controller/config.rb
- lib/sorcery/controller/submodules/activity_logging.rb
- lib/sorcery/controller/submodules/brute_force_protection.rb
- lib/sorcery/controller/submodules/http_basic_auth.rb
- lib/sorcery/controller/submodules/remember_me.rb
- lib/sorcery/controller/submodules/session_timeout.rb
Gets rid of a few FIXME's.
Set has been in Ruby forever, and it supports the few methods already used on the existing arrays (`<<`, `find`, `each`).
> Use Set to ensure unique arrays

- .travis.yml
- Gemfile
- gemfiles/rails_52.gemfile
- gemfiles/rails_60.gemfile
- spec/rails_app/app/controllers/application_controller.rb
- spec/rails_app/app/controllers/sorcery_controller.rb
- spec/support/migration_helper.rb
It adds Rails 6 to TravisCI.
This pull request also contains two changes to fix failing tests with Rails 6.
- Since the usage of `MigrationContext` was changed in rails/rails#36439, adds a branch to MigrationHelper.
- We are loading 'rails/all' in our test code, it implicitly load action_text from Rails 6. ActionText requires ApplicationController, adds it.
- ref: https://github.com/rails/rails/blob/v6.0.3/actiontext/lib/action_text/engine.rb#L50
> Add support for Rails 6

- lib/generators/sorcery/helpers.rb
- lib/generators/sorcery/templates/migration/activity_logging.rb
- lib/generators/sorcery/templates/migration/brute_force_protection.rb
- lib/generators/sorcery/templates/migration/core.rb
- lib/generators/sorcery/templates/migration/external.rb
- lib/generators/sorcery/templates/migration/magic_login.rb
- lib/generators/sorcery/templates/migration/remember_me.rb
- lib/generators/sorcery/templates/migration/reset_password.rb
- lib/generators/sorcery/templates/migration/user_activation.rb
Example: "ExampleNameSpace::User" parameter which will generate a table migration with "example_name_space_user" as the table name.
It's my first shot at helping out with some open source work, so I hope this is a useful starting contribution!
> Updated the generators to allow name spaced models to be passed in.

- lib/generators/sorcery/templates/initializer.rb
- lib/sorcery/providers/line.rb
Support for LINE login v2.1. ref: https://github.com/Sorcery/sorcery/pull/80  
doc -> https://developers.line.biz/en/docs/line-login/integrate-line-login/#login-flow
I proposed because I need bot_prompt function. It's enable you to add [LINE Bot](https://developers.line.biz/en/docs/messaging-api/overview/) when login with line.
https://github.com/Sorcery/sorcery/pull/80#issuecomment-327351210
> LINE is the most popular messaging application in Japan. But, it is not popular outside Japan.
LINE is similar to WhatsApp or Facebook Messenger.
About 70% of Japanese are using it, and it is used for 500 million people all over the world.
https://en.wikipedia.org/wiki/Line_(software)
> Support line login v2.1

- spec/controllers/controller_oauth2_spec.rb
- spec/controllers/controller_oauth_spec.rb
These tests will fail when run individually, so I fix them.
```console
$ bundle exec rspec spec/controllers/controller_oauth2_spec.rb:118
Failures:
1) SorceryController with OAuth features when callback_url begin with http:// login_at redirects correctly
Failure/Error: expect(response).to redirect_to("https://www.facebook.com/v2.2/dialog/oauth?client_id=#{::Sorcery::Controller::Config.facebook.key}&display=page&redirect_uri=http%3A%2F%2Ftest.host%2Foauth%2Ftwitter%2Fcallback&response_type=code&scope=email&state")
Expected response to be a redirect to <https://www.facebook.com/v2.2/dialog/oauth?client_id=eYVNBjBDi33aa9GkA3w&display=page&redirect_uri=http%3A%2F%2Ftest.host%2Foauth%2Ftwitter%2Fcallback&response_type=code&scope=email&state> but was a redirect to …
```
> Fix failing isolated tests

- CHANGELOG.md
- lib/generators/sorcery/templates/initializer.rb
- lib/sorcery/controller/submodules/external.rb
- lib/sorcery/providers/battlenet.rb
- spec/controllers/controller_oauth2_spec.rb
- spec/rails_app/app/controllers/sorcery_controller.rb
- spec/rails_app/config/routes.rb
I Added BattleNet as OAuth Provider as documented in theri api docu and tested it local.
> Add Battlenet Provider

- README.md
The link to the inch-ci badge in README.md because it was dead.
- Link: http://inch-ci.org/github/Sorcery/sorcery.svg?branch=master
It seems that `inch-ci.org` is not working, and cannot access the site from the following URL.
- Main site: https://inch-ci.org/
The badge was not showing up in README.md for these reasons, so I removed it to improve the documentation.
Please ensure your pull request includes the following:
> Removed the link to inch-ci badge in README.md because it wad dead

- lib/generators/sorcery/helpers.rb
The generated result of `bin/rails g sorcery:install` command is incorrect.
Current generated table name is `User`, but correct table name is `users`.
Current generated result
```ruby
class SorceryCore < ActiveRecord::Migration[6.1]
def change
create_table :User do |t|
t.string :email,            null: false
t.string :crypted_password
t.string :salt
t.timestamps                null: false
end
add_index :User, :email, unique: true
end
end
```
Generated result after modification
```ruby
class SorceryCore < ActiveRecord::Migration[6.1]
def change
create_table :users do |t|
t.string :email,            null: false
t.string :crypted_password
t.string :salt
t.timestamps                null: false
end
add_index :users, :email, unique: true
end
end
```
> Fixed default table name in migration file

- lib/generators/sorcery/templates/initializer.rb
The `remember_me` attributes were missing in the initialized configuration.
> Add missing remember_me attributes to config

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/ruby.yml
- gemfiles/rails_61.gemfile
- gemfiles/rails_70.gemfile
Currently the builds are broken due to changes in how net/smtp is included in ruby itself. Updating the version matrices and gemfiles to address these changes.
> Fix broken builds (net/smtp)

- CHANGELOG.md
- lib/sorcery/controller/submodules/external.rb
- spec/providers/examples_spec.rb
- spec/support/providers/examples.rb
When the external provider is specified as Okta, we get errors of the form `uninitialized constant Sorcery::Providers::Oktum`. The reason for this is that in the external providers file, the code was recently changed from using `capitalize` to `classify`. Unfortunately `'okta'.classify` resolves to 'Oktum' in ruby, causing this error.
Linked issue: https://github.com/Sorcery/sorcery/issues/306
> Fix the way the external provider class is instantiated for providers with plural names

- CHANGELOG.md
- lib/sorcery/controller/submodules/external.rb
Since 7.0, Rails protects against redirecting to external hosts
https://api.rubyonrails.org/classes/ActionController/Redirecting.html#method-i-redirect_to-label-Open+Redirect+protection
This change adapts to this by adding the option `allow_other_host` to the method call
> adapt to Rails 7.0 defaults

- CHANGELOG.md
- sorcery.gemspec
Please ensure your pull request includes the following:
Fixes #317
> Update version lock for oauth2 to v2 per v1 deprecation

- CHANGELOG.md
- lib/sorcery/model/submodules/reset_password.rb
- spec/shared_examples/user_reset_password_shared_examples.rb
Close #329
When calling `@user.change_password!("")` or `@user.change_password!(nil)`, a `ArgumentError` exception is now raised, because the password is missing, so it won't be modified.
Please ensure your pull request includes the following:
> Raise ArgumentError when calling change_password! with blank password

- CHANGELOG.md
- lib/generators/sorcery/install_generator.rb
There's no need to call `inject_sorcery_to_model` in the previous method, since the generators execute all public methods in order.
That's why we had an error in the logs: the method was called twice.
Close #265
> Remove duplicate method in InstallGenerator

- .github/workflows/ruby.yml
- .gitignore
- CHANGELOG.md
- gemfiles/rails_52.gemfile
- gemfiles/rails_61.gemfile
- gemfiles/rails_70.gemfile
- gemfiles/rails_71.gemfile
- sorcery.gemspec
- spec/controllers/controller_oauth2_spec.rb
- spec/controllers/controller_oauth_spec.rb
- spec/controllers/controller_session_timeout_spec.rb
- spec/controllers/controller_spec.rb
Now, Ruby 2.7 is EOL, and Rails 6.0 is also EOL.
So, I changed the CI settings to support only those higher versions and made the changes necessary to pass the tests.
CI result is [here](https://github.com/willnet/sorcery/actions/runs/7724024577).
Fix #340
> Change CI settings for support Ruby3.0+ Rails6.1+ 

- CHANGELOG.md
- sorcery.gemspec
This commit is related to https://github.com/Sorcery/sorcery/issues/340. In https://github.com/Sorcery/sorcery/pull/357, we limited CI support to Ruby 3.0 and above, but in the gemspec, we still had dependencies set for older Ruby versions.
> Bump up required ruby version to 3.0.0

- CHANGELOG.md
- sorcery.gemspec
This allows rubygems.org to display useful shortcuts:
> Add metadata to gemspec

- CHANGELOG.md
- sorcery.gemspec
- spec/spec_helper.rb
I couldn’t find any code using SimpleCov, other than the commented-out sections removed in this commit, so it seems SimpleCov is not currently in use.
> Remove unused SimpleCov

- .github/workflows/ruby.yml
- CHANGELOG.md
- gemfiles/rails_61.gemfile
- gemfiles/rails_70.gemfile
- lib/sorcery/adapters/mongoid_adapter.rb
- sorcery.gemspec
- spec/support/migration_helper.rb
Sorcery only supports the currently officially supported versions of Ruby and Rails.
Also remove conditionals for Rails versions older than 7.0, and mongoid versions older than 4.0
Mongoid 3.x is no longer relevant since its latest release (v3.1.7) depends on `activemodel ~> 3.2`, which is incompatible with current versions of Sorcery. See: https://github.com/mongodb/mongoid/blob/v3.1.7/mongoid.gemspec#L22
> Drop support for versions below Ruby 3.2 and Rails 7.1

- CHANGELOG.md
- spec/spec_helper.rb
The `rails-controller-testing` gem provided helper methods for controller tests up to Rails 4.2. This condition was used to support testing with both Rails 4.2 and Rails 5+. Since we no longer test with Rails versions below 5, the condition is no longer necessary.
ref: https://github.com/Sorcery/sorcery/pull/21
> Remove check for rails-controller-testing gem

- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.md
- MAINTAINING.md
- sorcery.gemspec
Currently, our policy requires manually adding changes to CHANGELOG.md for every PR on GitHub. This often causes conflicts when multiple PRs are open, and merging one of them leads to conflicts in all the others. Additionally, resolving these conflicts after approval requires re-approval, increasing the maintenance burden.
GitHub’s Releases page now supports automatic generation of changelogs. Going forward, we’d like to rely on this feature and stop manually writing the Changelog to reduce maintenance overhead.
> Stop the policy of manually updating the Changelog per PR

- lib/generators/sorcery/templates/initializer.rb
The activity_logging attribute was missing in the initialized configuration.
> Add missing activity_logging attribute to config

- lib/sorcery/test_helpers/internal.rb
- spec/controllers/controller_brute_force_protection_spec.rb
- spec/controllers/controller_http_basic_auth_spec.rb
- spec/controllers/controller_oauth2_spec.rb
- spec/controllers/controller_oauth_spec.rb
- spec/controllers/controller_remember_me_spec.rb
- spec/controllers/controller_session_timeout_spec.rb
- spec/controllers/controller_spec.rb
- spec/shared_examples/user_brute_force_protection_shared_examples.rb
- spec/shared_examples/user_oauth_shared_examples.rb
- spec/shared_examples/user_shared_examples.rb
Previously used domains like "blabla.com", "bla.com", and "bar.com" could exist in reality. Since IANA reserves example.com for documentation and examples, I replaced them with example.com whenever possible.
The exception is test.host, which Rails uses as the default domain in tests (see: https://github.com/rails/rails/blob/d09c4bbfcadcd6b3af847a11608a63c0718158ed/actionpack/lib/action_dispatch/testing/test_request.rb#L11). Simply changing it to example.com causes tests to fail. While adding the following snippet to `spec_helper.rb` would make the tests pass, I decided to leave it as is since the motivation isn’t strong enough:
```ruby
config.before(:each, type: :controller) do
request.host = 'example.com'
end
```
related url: https://github.com/Sorcery/sorcery/pull/387#discussion_r2264873 …
> Change test domains to use "example.com" wherever possible

- .github/workflows/ruby.yml
The latest version of actions/checkout is v5 now.
ref: https://github.com/actions/checkout
> Update actions/checkout to the latest version
