Sorcery/sorcery

README.md
Moved from / closes [#797](https://github.com/NoamB/sorcery/pull/797)
=> Update Badges / README.md

lib/generators/sorcery/templates/initializer.rb, lib/sorcery/controller/submodules/external.rb, lib/sorcery/providers/github.rb, lib/sorcery/providers/slack.rb, sorcery.gemspec, spec/controllers/controller_oauth2_spec.rb, spec/rails_app/app/controllers/sorcery_controller.rb, spec/rails_app/config/routes.rb, spec/shared_examples/user_shared_examples.rb
Just write a new provider to slack oauth2.  tests are green.
=> Slack auth

CHANGELOG.md, lib/generators/sorcery/templates/initializer.rb, lib/sorcery/controller/submodules/external.rb, lib/sorcery/providers/wechat.rb, spec/controllers/controller_oauth2_spec.rb, spec/rails_app/app/controllers/sorcery_controller.rb, spec/rails_app/config/routes.rb
Add Wechat provider. 😄 
Resolved #27
=> Add Wechat provider

CHANGELOG.md, lib/sorcery/model/submodules/brute_force_protection.rb, spec/shared_examples/user_brute_force_protection_shared_examples.rb
I fixed https://github.com/Sorcery/sorcery/issues/14
=> Rename conflicted methods

lib/sorcery/providers/linkedin.rb, lib/sorcery/version.rb
0.10.0 breaks linkedin due to how id was added to the fields.
=> Hotfix LinkedIn provider

CHANGELOG.md, sorcery.gemspec
Per [CVE-2017-17042](https://nvd.nist.gov/vuln/detail/CVE-2017-17042)
=> Update YARD dependency

Gemfile, lib/generators/sorcery/install_generator.rb, spec/active_record/user_activation_spec.rb, spec/active_record/user_activity_logging_spec.rb, spec/active_record/user_brute_force_protection_spec.rb, spec/active_record/user_magic_login_spec.rb, spec/active_record/user_oauth_spec.rb, spec/active_record/user_remember_me_spec.rb, spec/active_record/user_reset_password_spec.rb, spec/active_record/user_spec.rb, spec/controllers/controller_http_basic_auth_spec.rb, spec/controllers/controller_oauth2_spec.rb, spec/controllers/controller_oauth_spec.rb, spec/controllers/controller_session_timeout_spec.rb, spec/controllers/controller_spec.rb, spec/orm/active_record.rb, spec/rails_app/config/application.rb, spec/rails_app/config/initializers/secret_token.rb, spec/rails_app/config/secrets.yml, spec/shared_examples/user_shared_examples.rb, spec/support/migration_helper.rb
This fixes all the specs to support Rails 5.2 and Ruby 2.5. This also fixes any deprecation warnings raised for Rails 6.
=> Rails 5.2 support

lib/sorcery/model.rb, spec/shared_examples/user_shared_examples.rb
#77 was merged with breaking CI, and should be fixed or reverted.
=> Revert "Namespace class method #encrypt"

CHANGELOG.md, lib/sorcery/model/submodules/external.rb
Hi, I've resolved the issue related to module based classes for authentication class on external submodule.
Related to issue #146
=> demodulize added on authentication class name association name fetch

CHANGELOG.md, README.md
Anyone can read why [here](https://docs.gitlab.com/ee/user/project/import/gemnasium.html#why-is-gemnasium-com-closed).
=> Remove gemnasium badge

CHANGELOG.md
=> Move changelog entries for recent pulls to HEAD instead of v0.12.0

lib/sorcery/engine.rb
Fixes issue introduced by #133.
=> Fix Sorcery::Controller not being correctly included by ActionController::Base

lib/sorcery/model/submodules/magic_login.rb
=> Allow load_from_magic_login_token to accept a block

CHANGELOG.md, lib/generators/sorcery/templates/initializer.rb, lib/sorcery/providers/linkedin.rb
=> Update LinkedIn to use OAuth 2

lib/sorcery/controller.rb, spec/controllers/controller_spec.rb
(previous code skipped XHR requests, but not all JSON requests are XHR)
=> Don't :return_to JSON requests after login.

lib/generators/sorcery/templates/migration/core.rb
PR does not change anything functionally. Just a minor simplification of a core migration template.
=> Inline index definition in core migration

CHANGELOG.md
=> Update changelog with changes from #281

CHANGELOG.md, lib/sorcery/adapters/mongoid_adapter.rb
Update mongoid adapter to use splat operator for options
Fixes #270 
Thanks to @ccokme for the fix and test application
=> Fix MongoID adapter breaking on save

CHANGELOG.md, lib/sorcery/model.rb
=> Fix valid_password? not using configured values when called alone

sorcery.gemspec
=> Loosen oauth version lock per @pboling feedback on issue #317

sorcery.gemspec
test-unit was no longer being used
=> Remove test-unit from development dependency
